= SimHub Property Server & Computed Properties
:toc:
:sectnums:
ifdef::env-github[]
:tip-caption: :bulb:
:warning-caption: :warning:
endif::[]
ifndef::env-github[]
:tip-caption: 💡
:warning-caption: ⚠️
endif::[]

TIP: Always read the *correct version* of the documentation, which matches the version of the plugin that you have installed. To do so, use the dropdown in the top left, which usually contains the value "main". Select the "tag" that matches your installed version.


== About

This project offers two plugins for https://www.simhubdash.com/[SimHub].

=== SimHub Property Server

Allows access to SimHub properties via a tcp connection (thus: for other applications).

Other applications can subscribe for property changes. They will then receive updates each time, when the value of a subscribed property changes. Clients can also trigger SimHub Controls and SimHub Control Mapper Roles, thus trigger actions inside SimHub or the simulation.

One use case is my project https://github.com/pre-martin/StreamDeckSimHubPlugin[StreamDeckSimHubPlugin], which allows updating the state of Stream Deck keys via SimHub properties, and of course triggering of SimHub Controls and SimHub Control Mapper Roles.

=== Computed Properties

This is a really powerful plugin: It allows user-defined JavaScript code to be executed within SimHub.

User-defined code can be executed for example, when another property changes its value. Or this code can be triggered via SimHub Controls or SimHub Control Mapper Roles, which also includes the Stream Deck as a source, if my plugin for Stream Deck, the https://github.com/pre-martin/StreamDeckSimHubPlugin[StreamDeckSimHubPlugin], is installed.

A possible use case could be, that you press a specific Stream Deck key, and your user-defined code in SimHub starts to do some calculations, like calculating tyre pressure differences and propose new values for your next pit stop. These new values can be exposed via new SimHub properties (defined by your code), so that you can display them for example on SimHub dashes or on your Stream Deck.


== Installation

WARNING: To download, do not use the green button! Instead, click on "Releases" on the right side and download the file `PropertyServer.dll`.

The plugin requires at least SimHub version **9.6.0**.

Simply copy the file `PropertyServer.dll` into the root directory of your SimHub installation. After having launched SimHub, the plugin has to be activated under "_Settings_ > _Plugins_" (usually SimHub will autodetect the plugin and ask at startup, if the plugin shall be activated).

Optionally, the checkbox "_Show in left menu_" can be activated. This will show an entry named "_Property Server_" and/or "_Computed Properties_" in the left menu bar, which allows to interact with the plugins. If "_Show in left menu_" is not enabled, the plugins can be found under "_Additional Plugins_ > _Property Server_" and "_Additional Plugins_ > _Computed Properties_".

After installation, the checkbox "_Show in left menu_" can be found under "_Settings_ > _Plugins_".


== Usage

Both plugins have their own sub-pages for their documentation:

link:doc/PropertyServer/PropertyServer.adoc[Go to SimHub Property Server]. This documentation is mainly relevant if you are a software developer and want to access SimHub from other applications, or if you want to know details about ShakeIt Properties and their potential problems (“Repair ShakeIt Profiles”).

link:doc/ComputedProperties/ComputedProperties.adoc[Go to Computed Properties].
