<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>SimHub.Plugins</RootNamespace>
    <AssemblyName>PropertyServer</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <Deterministic>true</Deterministic>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="System.Net.Http" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="GameReaderCommon">
      <HintPath>..\SimHub\GameReaderCommon.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="log4net">
      <HintPath>..\SimHub\log4net.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="WoteverLocalization">
      <HintPath>..\SimHub\WoteverLocalization.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="SimHub.Plugins">
      <HintPath>..\SimHub\SimHub.Plugins.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Newtonsoft.Json">
      <HintPath>..\SimHub\Newtonsoft.Json.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="MahApps.Metro">
      <HintPath>..\SimHub\MahApps.Metro.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="MahApps.Metro.SimpleChildWindow">
      <HintPath>..\SimHub\MahApps.Metro.SimpleChildWindow.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Jint">
      <HintPath>..\SimHub\Jint.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Acornima">
      <HintPath>..\SimHub\Acornima.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="IcsSharpCode.AvalonEdit">
      <HintPath>..\SimHub\ICSharpCode.AvalonEdit.dll</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>

</Project>
