= ShakeIt Duplicate Finder
:toc:
:sectnums:

== Description

Finds duplicate Guids in SimHub ShakeIt profiles.

Duplicate Guids are a problem, if you are using the SimHub Property Server plugin or the Stream Deck SimHub plugin to access SimHub ShakeIt effect groups or effects.

== Usage

`ShakeIt.DuplicateFinder.exe <SimHub>\PluginsData\Common\ShakeITBassShakersSettings.json`

replace `<SimHub>` with the root directory of your SimHub installation. Probably `C:\Program Files (x86)\SimHub`.

The tool will then output a list of elemens with duplicate Guid:

----
Analyzing 5 profiles
2 duplicates for guid 0035c043-88ce-4ece-bde1-43c07b5cbf14
  Test profile / RPM Test / ACC v1 / MAX RPM   (INPUT - Base 28Hz / High 18Hz)
  Test profile / RPM Test / ACC v2 / MAX RPM   (INPUT - Base 48Hz / High 18Hz)
----

In this case, the Guid of the second entry should be replaced.

== How to replace Guids

. Exit SimHub. Be sure that it is not minimized to the tray bar!
. Use an editor like Notepad++ and open the same file as above.
. Insert new values for the attribute `ContainerId` in the JSON file.